import json
import csv
import io
from typing import Dict, Any
from fpdf import FPDF
from services.currency_service import currency_service

class PDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(15, 23, 42)  # Deep Navy
        self.cell(0, 10, "AI SMART TOURISM & TRAVEL RECOMMENDATION SYSTEM", border=0, align="C")
        self.ln(6)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(100, 116, 139)
        self.cell(0, 6, "Your Journey. Your Interests. Your AI-Powered Trip.", border=0, align="C")
        self.ln(10)
        self.set_draw_color(226, 232, 240)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Generated by AI Smart Tourism Platform | Page {self.page_no()}/{{nb}}", 0, 0, "C")


def clean_pdf_text(text: str) -> str:
    if not text:
        return ""
    # Replace Rupee symbol with INR
    s = str(text).replace("₹", "INR ").replace("€", "EUR ").replace("£", "GBP ")
    # Replace curly quotes / dashes
    s = s.replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'").replace("–", "-").replace("—", "-")
    return s.encode('latin-1', 'replace').decode('latin-1')

class ExportService:
    @staticmethod
    def generate_pdf(trip_data: Dict[str, Any]) -> bytes:
        """Generates a styled, multi-section PDF itinerary document."""
        pdf = PDFReport()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        destination = clean_pdf_text(trip_data.get("destination", "Trip Plan"))
        dates = clean_pdf_text(f"{trip_data.get('start_date', '')} to {trip_data.get('end_date', '')}")
        travelers = trip_data.get("travelers", 1)
        budget = trip_data.get("budget", 0)
        curr = trip_data.get("currency", "INR")
        costs = trip_data.get("estimated_costs", {})
        total_cost = costs.get("total_estimated", 0)

        # Title Box
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 12, clean_pdf_text(f"Itinerary: {destination}"), ln=True)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(0, 6, clean_pdf_text(f"Dates: {dates} | Duration: {trip_data.get('days', 1)} Days | Travelers: {travelers}"), ln=True)
        pdf.cell(0, 6, clean_pdf_text(f"Total Budget: {currency_service.format_currency(budget, curr)} | Estimated Cost: {currency_service.format_currency(total_cost, curr)}"), ln=True)
        pdf.ln(5)

        # AI Summary
        if trip_data.get("destination_summary"):
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(13, 148, 136)  # Teal
            pdf.set_x(pdf.l_margin)
            pdf.cell(pdf.epw, 8, "Destination Overview", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(51, 65, 85)
            summary_clean = clean_pdf_text(trip_data['destination_summary'])
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(pdf.epw, 6, summary_clean)
            pdf.ln(4)

        # Day-by-Day Timeline
        itinerary = trip_data.get("itinerary", [])
        if itinerary:
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(249, 115, 22)  # Sunset Orange
            pdf.set_x(pdf.l_margin)
            pdf.cell(pdf.epw, 10, "Day-by-Day Itinerary", ln=True)

            for day in itinerary:
                day_num = day.get("day", 1)
                theme = day.get("theme", f"Day {day_num} Highlights")
                date_str = day.get("date", "")

                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(15, 23, 42)
                theme_clean = clean_pdf_text(f"Day {day_num} ({date_str}) - {theme}")
                pdf.set_x(pdf.l_margin)
                pdf.cell(pdf.epw, 8, theme_clean, ln=True)

                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(71, 85, 105)

                for period_key, label in [("morning", "Morning"), ("afternoon", "Afternoon"), ("evening", "Evening")]:
                    period = day.get(period_key, {})
                    if period:
                        act = clean_pdf_text(period.get("activity", ""))
                        time_str = clean_pdf_text(period.get("time", ""))
                        meal = clean_pdf_text(period.get("meal_recommendation", ""))
                        
                        pdf.set_x(pdf.l_margin)
                        pdf.set_font("Helvetica", "B", 9)
                        pdf.cell(25, 5, f"  * {label}:", ln=False)
                        pdf.set_font("Helvetica", "", 9)
                        pdf.cell(pdf.epw - 25, 5, clean_pdf_text(f"{time_str} - {act}"), ln=True)
                        if meal:
                            pdf.set_x(pdf.l_margin + 25)
                            pdf.set_font("Helvetica", "I", 8)
                            pdf.cell(pdf.epw - 25, 4, clean_pdf_text(f"Dining tip: {meal}"), ln=True)
                pdf.ln(3)

        # Budget Breakdown
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(13, 148, 136)
        pdf.set_x(pdf.l_margin)
        pdf.cell(pdf.epw, 8, "Budget & Cost Estimates", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)

        for cat, label in [
            ("transportation", "Transportation"),
            ("accommodation", "Accommodation"),
            ("food", "Food & Dining"),
            ("activities", "Activities & Sightseeing"),
            ("local_travel", "Local City Transit"),
            ("miscellaneous", "Buffer / Miscellaneous")
        ]:
            val = costs.get(cat, 0)
            pdf.set_x(pdf.l_margin)
            pdf.cell(70, 5, f"- {label}:", ln=False)
            pdf.cell(pdf.epw - 70, 5, clean_pdf_text(f"{currency_service.format_currency(val, curr)}"), ln=True)

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_x(pdf.l_margin)
        pdf.cell(70, 6, "Total Estimated Cost:", ln=False)
        pdf.cell(pdf.epw - 70, 6, clean_pdf_text(f"{currency_service.format_currency(total_cost, curr)}"), ln=True)
        pdf.ln(4)

        # Travel Tips
        tips = trip_data.get("travel_tips", [])
        if tips:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(15, 23, 42)
            pdf.set_x(pdf.l_margin)
            pdf.cell(pdf.epw, 8, "Essential Travel Tips", ln=True)
            pdf.set_font("Helvetica", "", 9)
            for tip in tips:
                clean_tip = clean_pdf_text(tip)
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(pdf.epw, 5, f"* {clean_tip}")

        return bytes(pdf.output())

    @staticmethod
    def generate_json(trip_data: Dict[str, Any]) -> str:
        """Returns JSON formatted string of trip data."""
        return json.dumps(trip_data, indent=2, default=str)

    @staticmethod
    def generate_csv(trip_data: Dict[str, Any]) -> str:
        """Generates CSV itinerary schedule."""
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["Day", "Date", "Period", "Time", "Activity", "Location", "Est Cost", "Meal Tip"])

        itinerary = trip_data.get("itinerary", [])
        for day in itinerary:
            day_num = day.get("day", 1)
            cur_date = day.get("date", "")
            for period_name in ["morning", "afternoon", "evening"]:
                period = day.get(period_name, {})
                if period:
                    writer.writerow([
                        day_num,
                        cur_date,
                        period_name.capitalize(),
                        period.get("time", ""),
                        period.get("activity", ""),
                        period.get("location", ""),
                        period.get("estimated_cost", 0),
                        period.get("meal_recommendation", "")
                    ])

        return output.getvalue()

export_service = ExportService()
